name: Publish Docker image to google registry

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the repo
        uses: actions/checkout@v3


      # - id: 'auth'
      #   name: 'Authenticate to Google Cloud'
      #   uses: 'google-github-actions/auth@v1'
      #   with:
      #     service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
      #     credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          registry: us-east1-docker.pkg.dev
          project_id: chooeki
          image_name: chatgpt-next-web
          image_tag: latest
          dockerfile: ./Dockerfile
          context: ./


        